[package]
name = "esp32c3"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "ESP32-C3 SoC model: memory map, peripherals, machine"

[dependencies]
emu-core = { path = "../emu-core" }
esp-periph = { path = "../esp-periph" }
riscv-rv32 = { path = "../riscv-rv32" }
esp-soc = { path = "../esp-soc" }
esp-wifi = { path = "../esp-wifi" }
