[env]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1
framework = arduino
build_flags = -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
  adafruit/Adafruit BusIO@1.17.4
  https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library.git#a98850b815bf9696c8ffdc2a0f89d657c52dd44b
[env:s3]
board = esp32-s3-devkitc-1
[env:c3]
board = esp32-c3-devkitm-1
[env:c6]
board = esp32-c6-devkitc-1
