[platformio]
src_dir = main

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32dev
framework = espidf
board_build.sdkconfig = sdkconfig
